
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 24 10:58:37 MST 2019
//----------------------------------------------------

package fuentes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DEFECTO = 69;
  public static final int EINICIAL = 27;
  public static final int CONJUNTO = 13;
  public static final int MTABLA = 32;
  public static final int PYCOMA = 55;
  public static final int GRAFICO = 18;
  public static final int SI = 65;
  public static final int EFINAL = 28;
  public static final int ELEMENTOESTADO = 59;
  public static final int AFN = 26;
  public static final int OPRINPAL = 34;
  public static final int ELEMENTO = 58;
  public static final int SELEC = 67;
  public static final int POT = 9;
  public static final int POR = 7;
  public static final int AFD = 25;
  public static final int FUNCION = 22;
  public static final int VALIDAR = 23;
  public static final int PAR_C = 51;
  public static final int PAR_A = 50;
  public static final int NOT = 44;
  public static final int DEC = 47;
  public static final int DPUNTO = 56;
  public static final int AUTOMATA = 11;
  public static final int ER = 31;
  public static final int BOOLEANO = 12;
  public static final int BELOWE = 38;
  public static final int HACER = 64;
  public static final int PARA = 70;
  public static final int COMA = 54;
  public static final int ENTERO = 3;
  public static final int DETENER = 71;
  public static final int EQUAL = 39;
  public static final int ORDEN = 33;
  public static final int DECIMAL = 4;
  public static final int FIN = 16;
  public static final int HASTA = 62;
  public static final int DIV = 8;
  public static final int INT1 = 48;
  public static final int ABOVEE = 37;
  public static final int EXPRESION = 15;
  public static final int MENOS = 6;
  public static final int MAS = 5;
  public static final int NEQUAL = 40;
  public static final int OREXP = 90;
  public static final int EOF = 0;
  public static final int MIENTRAS = 61;
  public static final int MOSTRAR = 20;
  public static final int CHAR1 = 49;
  public static final int CON = 24;
  public static final int INI = 19;
  public static final int ABOVE = 35;
  public static final int TRANSICION = 29;
  public static final int INC = 46;
  public static final int BELOW = 36;
  public static final int LLAV_C = 53;
  public static final int LLAV_A = 52;
  public static final int OR = 41;
  public static final int error = 1;
  public static final int ENTER = 60;
  public static final int ID = 2;
  public static final int CONTINUA = 72;
  public static final int SINO = 66;
  public static final int CASO = 68;
  public static final int HACIA = 30;
  public static final int FLOTANTE = 17;
  public static final int ASIG = 57;
  public static final int ESTADO = 14;
  public static final int ALFABETO = 10;
  public static final int AND = 42;
  public static final int NUEVO = 21;
  public static final int NAND = 45;
  public static final int XOR = 43;
  public static final int REPETIR = 63;
}

