
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fuentes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT1 = 47;
  public static final int AUTOMATA = 11;
  public static final int CASO = 64;
  public static final int POT = 9;
  public static final int CONJUNTO = 13;
  public static final int BELOWE = 37;
  public static final int POR = 7;
  public static final int SI = 61;
  public static final int ENTERO = 3;
  public static final int MOSTRAR = 20;
  public static final int FUNCION = 22;
  public static final int XOR = 42;
  public static final int CONTINUA = 68;
  public static final int FIN = 16;
  public static final int HASTA = 58;
  public static final int GRAFICO = 18;
  public static final int NOT = 43;
  public static final int AND = 41;
  public static final int MTABLA = 31;
  public static final int NAND = 44;
  public static final int INI = 19;
  public static final int SINO = 62;
  public static final int OR = 40;
  public static final int EFINAL = 28;
  public static final int MIENTRAS = 57;
  public static final int ABOVE = 34;
  public static final int INC = 45;
  public static final int DIV = 8;
  public static final int CHAR1 = 48;
  public static final int LLAV_C = 52;
  public static final int ID = 2;
  public static final int LLAV_A = 51;
  public static final int OPRINPAL = 33;
  public static final int PYCOMA = 54;
  public static final int ALFABETO = 10;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int ASIG = 56;
  public static final int EQUAL = 38;
  public static final int error = 1;
  public static final int COMA = 53;
  public static final int MENOS = 6;
  public static final int SELEC = 63;
  public static final int PAR_C = 50;
  public static final int PAR_A = 49;
  public static final int ER = 30;
  public static final int CON = 24;
  public static final int NUEVO = 21;
  public static final int ABOVEE = 36;
  public static final int DETENER = 67;
  public static final int HACIA = 29;
  public static final int BELOW = 35;
  public static final int NEQUAL = 39;
  public static final int DPUNTO = 55;
  public static final int ESTADO = 14;
  public static final int AFN = 26;
  public static final int REPETIR = 59;
  public static final int ORDEN = 32;
  public static final int HACER = 60;
  public static final int BOOLEANO = 12;
  public static final int PARA = 66;
  public static final int DEC = 46;
  public static final int EINICIAL = 27;
  public static final int AFD = 25;
  public static final int EXPRESION = 15;
  public static final int DEFECTO = 65;
  public static final int FLOTANTE = 17;
  public static final int VALIDAR = 23;
  public static final int MAS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "ALFABETO",
  "AUTOMATA",
  "BOOLEANO",
  "CONJUNTO",
  "ESTADO",
  "EXPRESION",
  "FIN",
  "FLOTANTE",
  "GRAFICO",
  "INI",
  "MOSTRAR",
  "NUEVO",
  "FUNCION",
  "VALIDAR",
  "CON",
  "AFD",
  "AFN",
  "EINICIAL",
  "EFINAL",
  "HACIA",
  "ER",
  "MTABLA",
  "ORDEN",
  "OPRINPAL",
  "ABOVE",
  "BELOW",
  "ABOVEE",
  "BELOWE",
  "EQUAL",
  "NEQUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "NAND",
  "INC",
  "DEC",
  "INT1",
  "CHAR1",
  "PAR_A",
  "PAR_C",
  "LLAV_A",
  "LLAV_C",
  "COMA",
  "PYCOMA",
  "DPUNTO",
  "ASIG",
  "MIENTRAS",
  "HASTA",
  "REPETIR",
  "HACER",
  "SI",
  "SINO",
  "SELEC",
  "CASO",
  "DEFECTO",
  "PARA",
  "DETENER",
  "CONTINUA"
  };
}

